spring:
  application:
    name: queue-receiver

server:
  port: 9030

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    enabled: true
#    healthcheck:
#      enabled: true
